# Generated by Django 4.2.27 on 2026-02-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default="Hi, I'm Riazul Islam", max_length=200)),
                ('hero_subtitle', models.CharField(default='Full Stack Developer', max_length=300)),
                ('hero_description', models.TextField(default='I build exceptional and accessible digital experiences for the web.')),
                ('hero_cta_text', models.CharField(default='Get In Touch', max_length=50)),
                ('hero_cta_link', models.CharField(default='/contact/', max_length=200)),
                ('about_title', models.CharField(default='About Me', max_length=100)),
                ('about_content', models.TextField(default="I'm a passionate full stack developer with expertise in modern web technologies.")),
                ('skills_title', models.CharField(default='My Skills', max_length=100)),
                ('skills_subtitle', models.CharField(default='Technologies I work with', max_length=200)),
                ('projects_title', models.CharField(default='Featured Projects', max_length=100)),
                ('projects_subtitle', models.CharField(default='Some of my recent work', max_length=200)),
                ('contact_title', models.CharField(default="Let's Work Together", max_length=100)),
                ('contact_subtitle', models.CharField(default="Have a project in mind? Let's discuss how we can help.", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Riazul Islam', max_length=100)),
                ('tagline', models.CharField(default='Full Stack Developer', max_length=200)),
                ('description', models.TextField(default='Passionate full stack developer specializing in Django, React, and modern web technologies.')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('years_experience', models.PositiveIntegerField(default=5)),
                ('projects_completed', models.PositiveIntegerField(default=50)),
                ('clients_served', models.PositiveIntegerField(default=20)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(default='contact@example.com', max_length=254)),
                ('phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(default='San Francisco, CA', max_length=100)),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords for SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
