"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Application definition
from decouple import config

SECRET_KEY = config('SECRET_KEY')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'jazzmin',
    'crispy_forms',
    'crispy_tailwind',
    
    # Local apps
    'apps.core',
    'apps.portfolio',
    'apps.skills',
    'apps.experience',
    'apps.blog',
    'apps.reviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database configuration will be in environment-specific files


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files configuration will be in environment-specific files

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin Admin Theme
JAZZMIN_SETTINGS = {
    'site_title': 'Portfolio Admin',
    'site_header': 'Portfolio Administration',
    'site_icon': 'fas fa-code',
    'welcome_sign': 'Welcome to Portfolio Admin',
    'copyright': 'Riazul Islam',
    
    'navigation': [
        {'model': 'core.SiteSettings', 'label': 'Site Settings'},
        {'model': 'core.ContactSubmission', 'label': 'Contact Messages'},
        {'model': 'core.HomePage', 'label': 'Home Page'},
        {'app': 'portfolio', 'label': 'Projects'},
        {'app': 'skills', 'label': 'Skills'},
        {'app': 'experience', 'label': 'Experience'},
        {'app': 'blog', 'label': 'Blog'},
        {'app': 'reviews', 'label': 'Reviews'},
    ],
    
    'hide_models': ['*'],
    'show_models': [
        'core.SiteSettings',
        'core.ContactSubmission', 
        'core.HomePage',
        'portfolio.Project',
        'portfolio.ProjectCategory',
        'skills.Skill',
        'skills.SkillCategory',
        'experience.Experience',
        'experience.Education',
        'blog.Post',
        'blog.Category',
        'reviews.Review',
    ],
    
    'order_with_respect_to': [
        'core.SiteSettings',
        'core.HomePage',
        'portfolio.ProjectCategory',
        'portfolio.Project',
        'skills.SkillCategory',
        'skills.Skill',
        'experience.Experience',
        'experience.Education',
        'blog.Category',
        'blog.Post',
        'reviews.Review',
        'core.ContactSubmission',
    ],
    
    'icon_settings': {
        'core.SiteSettings': 'fas fa-cog',
        'core.ContactSubmission': 'fas fa-envelope',
        'core.HomePage': 'fas fa-home',
        'portfolio.Project': 'fas fa-project-diagram',
        'portfolio.ProjectCategory': 'fas fa-folder',
        'skills.Skill': 'fas fa-tools',
        'skills.SkillCategory': 'fas fa-folder-open',
        'experience.Experience': 'fas fa-briefcase',
        'experience.Education': 'fas fa-graduation-cap',
        'blog.Post': 'fas fa-blog',
        'blog.Category': 'fas fa-tag',
        'reviews.Review': 'fas fa-star',
    },
    
    'changeform_format': 'horizontal_tabs',
    'add_form_format': 'horizontal',
    
    'button_classes': {
        'add': 'btn btn-primary',
        'save': 'btn btn-success',
        'delete': 'btn btn-danger',
        'cancel': 'btn btn-light',
    },
}
